-- ========= --
-- DW Design --
-- ========= --

-- Table: UDW_DIM_COUNTRY
CREATE TABLE UDW_DIM_COUNTRY (
    COUNTRY_CODE char(3)  NOT NULL,
    COUNTRY_NAME varchar2(100)  NOT NULL,
    REGION_NAME varchar2(100)  NOT NULL,
    CONSTRAINT UDW_DIM_COUNTRY_pk PRIMARY KEY (COUNTRY_CODE)
) ;
-- Table: UDW_DIM_GENDER
CREATE TABLE UDW_DIM_GENDER (
    GENDER_CODE char(1)  NOT NULL,
    GENDER_NAME varchar2(10)  NOT NULL,
    CONSTRAINT UDW_DIM_GENDER_pk PRIMARY KEY (GENDER_CODE)
) ;
-- Table: UDW_DIM_TIME
CREATE TABLE UDW_DIM_TIME (
    YEAR_CODE integer  NOT NULL,
    DECADE_NAME char(5)  NOT NULL,
    CONSTRAINT UDW_DIM_TIME_pk PRIMARY KEY (YEAR_CODE)
) ;
-- Table: UDW_FACT_POPULATION
CREATE TABLE UDW_FACT_POPULATION (
    YEAR_CODE integer  NOT NULL,
    GENDER_CODE char(1)  NOT NULL,
    COUNTRY_CODE char(3)  NOT NULL,
    DM_POP_TOT integer  NOT NULL,
    DM_POP_U5 integer  NOT NULL,
    DM_POP_ADLCNT integer  NOT NULL,
    DM_POP_15TO24 integer  NOT NULL,
    DM_POP_U18 integer  NOT NULL,
    CONSTRAINT UDW_FACT_POPULATION_pk PRIMARY KEY (YEAR_CODE,GENDER_CODE,COUNTRY_CODE)
) ;
ALTER TABLE UDW_FACT_POPULATION ADD CONSTRAINT UDW_DIM_COUNTRY_FACT_POP_FK
    FOREIGN KEY (COUNTRY_CODE)
    REFERENCES UDW_DIM_COUNTRY (COUNTRY_CODE);
ALTER TABLE UDW_FACT_POPULATION ADD CONSTRAINT UDW_DIM_GENDER_FACT_POP_FK
    FOREIGN KEY (GENDER_CODE)
    REFERENCES UDW_DIM_GENDER (GENDER_CODE);
ALTER TABLE UDW_FACT_POPULATION ADD CONSTRAINT UDW_DIM_TIME_FACT_POP_FK
    FOREIGN KEY (YEAR_CODE)
    REFERENCES UDW_DIM_TIME (YEAR_CODE);

-- ============== --
-- Data Ingestion --
-- ============== --

--Insert dimension table data first
-- Countries
INSERT INTO UDW_DIM_COUNTRY (COUNTRY_CODE, 
COUNTRY_NAME, REGION_NAME) 
SELECT DISTINCT SUBSTR(t.REF_AREA, 1, 3) AS COUNTRY_CODE 
            ,SUBSTR(t.REF_AREA, 6) AS COUNTRY_NAME 
            ,'Unknown' AS REGION_NAME 
        FROM hc848.UNICEF_RAW_DATA t 
       WHERE t.REF_AREA LIKE '___: %' 
         AND (t.INDICATOR LIKE 'NT_CF%' OR t.INDICATOR LIKE 'CME_%' OR t.INDICATOR LIKE 'DM_POP%' OR t.INDICATOR LIKE 'ED%' ) 
         AND NOT EXISTS( SELECT 1 FROM UDW_DIM_COUNTRY dc WHERE dc.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3));

--Insert dimension table data first
-- Gender
INSERT INTO UDW_DIM_GENDER (GENDER_CODE,  
GENDER_NAME) 
    SELECT DISTINCT CASE WHEN t.SEX LIKE '_: %' THEN SUBSTR(t.SEX, 1, 1) END AS GENDER_CODE 
          ,CASE WHEN t.SEX LIKE '_: %' THEN SUBSTR(t.SEX, 4) END AS GENDER_NAME 
      FROM hc848.UNICEF_RAW_DATA t 
     WHERE t.SEX LIKE '_: %' 
       AND (t.INDICATOR LIKE 'NT_CF%' OR t.INDICATOR LIKE 'CME_%' OR t.INDICATOR LIKE 'DM_POP%' OR t.INDICATOR LIKE 'ED%' ) 
       AND NOT EXISTS ( SELECT 1 FROM UDW_DIM_GENDER dg WHERE dg.GENDER_CODE = SUBSTR(t.SEX, 1, 1)) 

--Insert dimension table data first
-- Time
INSERT INTO UDW_DIM_TIME (YEAR_CODE, DECADE_NAME) 
SELECT DISTINCT SUBSTR(t.TIME_PERIOD,1,4) YEAR_CODE 
          , SUBSTR(t.TIME_PERIOD,1,3)||'0s' DECADE_NAME 
      FROM hc848.UNICEF_RAW_DATA t 
     WHERE (t.INDICATOR LIKE 'NT_CF%' OR t.INDICATOR LIKE 'CME_%' OR t.INDICATOR LIKE 'DM_POP%' OR t.INDICATOR LIKE 'ED%' ) 
       AND NOT EXISTS ( SELECT 1 FROM UDW_DIM_TIME dt WHERE dt.YEAR_CODE = SUBSTR(t.TIME_PERIOD,1,4) ) 
       ORDER BY YEAR_CODE; 
commit;

-- 
-- FACT_POPULATION 
--
--Update fact table after updating dimension tables

-- UDW_FACT_POPULATION
SELECT COUNT(*) FROM hc848.UNICEF_RAW_DATA t WHERE t.INDICATOR LIKE 'DM_POP%';
-- 357,054 raw records
-- 34,484 rows inserted.
INSERT INTO UDW_FACT_POPULATION (
    YEAR_CODE ,
    GENDER_CODE,
    COUNTRY_CODE,
    DM_POP_TOT,
    DM_POP_U5,
    DM_POP_ADLCNT,
    DM_POP_15TO24,
    DM_POP_U18
) 
SELECT 
     TIME_PERIOD            YEAR_CODE
    ,substr(t.SEX,1,1)      GENDER_CODE
    ,substr(t.REF_AREA,1,3) COUNTRY_CODE
    ,max(case when INDICATOR like 'DM_POP_TOT:%' then OBS_VALUE end)    * 1000 DM_POP_TOT
    ,max(case when INDICATOR like 'DM_POP_U5:%' then OBS_VALUE end)     * 1000 DM_POP_U5
    ,max(case when INDICATOR like 'DM_POP_ADLCNT:%' then OBS_VALUE end) * 1000 DM_POP_ADLCNT
    ,max(case when INDICATOR like 'DM_POP_15TO24:%' then OBS_VALUE end) * 1000 DM_POP_15TO24
    ,max(case when INDICATOR like 'DM_POP_U18:%' then OBS_VALUE end)    * 1000 DM_POP_U18
 FROM hc848.UNICEF_RAW_DATA t
WHERE t.INDICATOR LIKE 'DM_POP%' AND REGEXP_LIKE(TIME_PERIOD, '^[0-9]{4}$')
  AND EXISTS (SELECT 1 FROM UDW_DIM_TIME y WHERE y.YEAR_CODE = t.TIME_PERIOD)
  AND EXISTS (SELECT 1 FROM UDW_DIM_GENDER g WHERE g.GENDER_CODE = substr(t.SEX,1,1))
  AND EXISTS (SELECT 1 FROM UDW_DIM_COUNTRY c WHERE c.COUNTRY_CODE = substr(t.REF_AREA,1,3))
  AND NOT EXISTS (SELECT 1 FROM UDW_FACT_POPULATION f WHERE f.YEAR_CODE = t.TIME_PERIOD AND f.GENDER_CODE = substr(t.SEX,1,1) AND f.COUNTRY_CODE = substr(t.REF_AREA,1,3))
GROUP BY      
     TIME_PERIOD            
    ,substr(t.SEX,1,1)      
    ,substr(t.REF_AREA,1,3)
;
    

-- UDW_FACT_DEATH
SELECT COUNT(*) FROM hc848.UNICEF_RAW_DATA t WHERE t.INDICATOR LIKE 'CME_TMY%';
-- 299,574 raw records
-- 24,012 rows inserted. 
INSERT INTO udw_fact_death ( 
    YEAR_CODE , 
    GENDER_CODE , 
    COUNTRY_CODE , 
    CME_TMY0 ,
    CME_TMY0T4 ,
    CME_TMY10T14 , 
    CME_TMY10T19 ,
    CME_TMY15T19 , 
    CME_TMY5T9 , 
    CME_TMY1T4 , 
    CME_TMY20T24 , 
    CME_TMY5T14 , 
    CME_TMY5T24 , 
    CME_TMY15T24
) 
  SELECT TIME_PERIOD             year_code 
       ,SUBSTR(t.SEX, 1, 1)      gender_code 
       ,SUBSTR(t.REF_AREA, 1, 3) country_code 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY0:%' THEN OBS_VALUE END) CME_TMY0 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY0T4:%' THEN OBS_VALUE END) CME_TMY0T4 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY10T14:%' THEN OBS_VALUE END) CME_TMY10T14 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY10T19:%' THEN OBS_VALUE END) CME_TMY10T19 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY15T19:%' THEN OBS_VALUE END) CME_TMY15T19 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY5T9:%' THEN OBS_VALUE END) CME_TMY5T9 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY1T4:%' THEN OBS_VALUE END) CME_TMY1T4 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY20T24:%' THEN OBS_VALUE END) CME_TMY20T24 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY5T14:%' THEN OBS_VALUE END) CME_TMY5T14 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY5T24:%' THEN OBS_VALUE END) CME_TMY5T24 
       ,MAX(CASE WHEN INDICATOR LIKE 'CME_TMY15T24:%' THEN OBS_VALUE END) CME_TMY15T24 
        
  FROM hc848.UNICEF_RAW_DATA t 
WHERE t.INDICATOR LIKE 'CME_TMY%' AND REGEXP_LIKE(TIME_PERIOD, '^[0-9]{4}$')
   AND EXISTS (SELECT 1 FROM UDW_DIM_TIME y WHERE y.YEAR_CODE = t.TIME_PERIOD) 
   AND EXISTS (SELECT 1 FROM UDW_DIM_GENDER g WHERE g.GENDER_CODE = SUBSTR(t.SEX, 1, 1)) 
   AND EXISTS (SELECT 1 FROM UDW_DIM_COUNTRY c WHERE c.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3)) 
   AND NOT EXISTS (SELECT 1 FROM UDW_FACT_DEATH f WHERE f.YEAR_CODE = t.TIME_PERIOD  AND f.GENDER_CODE = SUBSTR(t.SEX, 1, 1) AND f.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3)) 
 GROUP BY TIME_PERIOD 
          ,SUBSTR(t.SEX, 1, 1) 
          ,SUBSTR(t.REF_AREA, 1, 3)
;

 
-- UDW_FACT_NUTRITION
SELECT COUNT(*) FROM hc848.UNICEF_RAW_DATA t WHERE t.INDICATOR LIKE 'NT_CF%';
-- 9,535 raw records
-- 700 rows inserted.
INSERT INTO UDW_FACT_NUTRITION ( 
    YEAR_CODE , 
    GENDER_CODE , 
    COUNTRY_CODE , 
    NT_CF_ASF , 
    NT_CF_BREASTMILK , 
    NT_CF_DAIRY , 
    NT_CF_EGGS , 
    NT_CF_FF , 
    NT_CF_GRAINS , 
    NT_CF_ISSSF_FL , 
    NT_CF_LEGUMES , 
    NT_CF_MAD , 
    NT_CF_MDD , 
    NT_CF_MMF , 
    NT_CF_OTHER_FV , 
    NT_CF_VITA , 
    NT_CF_ZEROFV 
)
  SELECT TIME_PERIOD             year_code 
       ,SUBSTR(t.SEX, 1, 1)      gender_code 
       ,SUBSTR(t.REF_AREA, 1, 3) country_code 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_ASF:%' THEN OBS_VALUE END) NT_CF_ASF 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_BREASTMILK:%' THEN OBS_VALUE END) NT_CF_BREASTMILK 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_DAIRY:%' THEN OBS_VALUE END) NT_CF_DAIRY 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_EGGS:%' THEN OBS_VALUE END) NT_CF_EGGS 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_FF:%' THEN OBS_VALUE END) NT_CF_FF 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_GRAINS:%' THEN OBS_VALUE END) NT_CF_GRAINS 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_ISSSF_FL:%' THEN OBS_VALUE END) NT_CF_ISSSF_FL 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_LEGUMES:%' THEN OBS_VALUE END) NT_CF_LEGUMES 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_MAD:%' THEN OBS_VALUE END) NT_CF_MAD 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_MDD:%' THEN OBS_VALUE END) NT_CF_MDD 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_MMF:%' THEN OBS_VALUE END) NT_CF_MMF 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_OTHER_FV:%' THEN OBS_VALUE END) NT_CF_OTHER_FV 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_VITA:%' THEN OBS_VALUE END) NT_CF_VITA 
       ,MAX(CASE WHEN INDICATOR LIKE 'NT_CF_ZEROFV:%' THEN OBS_VALUE END) NT_CF_ZEROFV 
  FROM hc848.UNICEF_RAW_DATA t 
 WHERE t.INDICATOR LIKE 'NT_CF%' AND REGEXP_LIKE(TIME_PERIOD, '^[0-9]{4}$')
   and EXISTS (SELECT 1 FROM UDW_DIM_TIME y WHERE y.YEAR_CODE = t.TIME_PERIOD) 
   AND EXISTS (SELECT 1 FROM UDW_DIM_GENDER g WHERE g.GENDER_CODE = SUBSTR(t.SEX, 1, 1)) 
   AND EXISTS (SELECT 1 FROM UDW_DIM_COUNTRY c WHERE c.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3)) 
   AND NOT EXISTS (SELECT 1 FROM UDW_FACT_NUTRITION f WHERE f.YEAR_CODE = t.TIME_PERIOD AND f.GENDER_CODE = SUBSTR(t.SEX, 1, 1) AND f.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3)) 
 GROUP BY TIME_PERIOD 
          ,SUBSTR(t.SEX, 1, 1) 
          ,SUBSTR(t.REF_AREA, 1, 3)
;
 
 
 
-- UDW_FACT_EDUCATION
SELECT COUNT(*) FROM hc848.UNICEF_RAW_DATA t WHERE t.INDICATOR LIKE 'ED%';
-- 7,151 raw records
-- 1,188 rows inserted. 
INSERT INTO UDW_FACT_EDUCATION ( 
    YEAR_CODE , 
    GENDER_CODE , 
    COUNTRY_CODE , 
    ED_15_24_LR , 
    ED_ANAR_L02 , 
    ED_ANAR_L1 , 
    ED_ANAR_L2 , 
    ED_ANAR_L3 , 
    ED_CR_L1 , 
    ED_CR_L2 , 
    ED_CR_L3 , 
    ED_MAT_G23 , 
    ED_MAT_L1 , 
    ED_MAT_L2 , 
    ED_READ_G23 , 
    ED_READ_L1 , 
    ED_READ_L2 , 
    ED_ROFST_L02 , 
    ED_ROFST_L1 , 
    ED_ROFST_L1_ADM , 
    ED_ROFST_L2 , 
    ED_ROFST_L2_ADM , 
    ED_ROFST_L3 , 
    ED_ROFST_L3_ADM 
) 
  SELECT TIME_PERIOD               year_code 
       ,SUBSTR(t.SEX, 1, 1)      gender_code 
       ,SUBSTR(t.REF_AREA, 1, 3) country_code 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_15_24_LR:%' THEN OBS_VALUE END) ED_15_24_LR 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ANAR_L02:%' THEN OBS_VALUE END) ED_ANAR_L02 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ANAR_L1:%' THEN OBS_VALUE END) ED_ANAR_L1 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ANAR_L2:%' THEN OBS_VALUE END) ED_ANAR_L2 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ANAR_L3:%' THEN OBS_VALUE END) ED_ANAR_L3 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_CR_L1:%' THEN OBS_VALUE END) ED_CR_L1 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_CR_L2:%' THEN OBS_VALUE END) ED_CR_L2 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_CR_L3:%' THEN OBS_VALUE END) ED_CR_L3 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_MAT_G23:%' THEN OBS_VALUE END) ED_MAT_G23 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_MAT_L1:%' THEN OBS_VALUE END) ED_MAT_L1 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_MAT_L2:%' THEN OBS_VALUE END) ED_MAT_L2 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_READ_G23:%' THEN OBS_VALUE END) ED_READ_G23 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_READ_L1:%' THEN OBS_VALUE END) ED_READ_L1 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_READ_L2:%' THEN OBS_VALUE END) ED_READ_L2 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFST_L02:%' THEN OBS_VALUE END) ED_ROFST_L02 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFST_L1:%' THEN OBS_VALUE END) ED_ROFST_L1 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFST_L1_ADM:%' THEN OBS_VALUE END) ED_ROFST_L1_ADM 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFST_L2:%' THEN OBS_VALUE END) ED_ROFST_L2 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFST_L2_ADM:%' THEN OBS_VALUE END) ED_ROFST_L2_ADM 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFSST_L3:%' THEN OBS_VALUE END) ED_ROFSST_L3 
       ,MAX(CASE WHEN INDICATOR LIKE 'ED_ROFST_L3_ADM:%' THEN OBS_VALUE END) ED_ROFST_L3_ADM 
  FROM hc848.UNICEF_RAW_DATA t 
 WHERE t.INDICATOR LIKE 'ED%' AND REGEXP_LIKE(TIME_PERIOD, '^[0-9]{4}$')
   AND EXISTS (SELECT 1 FROM UDW_DIM_TIME y WHERE y.YEAR_CODE = t.TIME_PERIOD) 
   AND EXISTS (SELECT 1 FROM UDW_DIM_GENDER g WHERE g.GENDER_CODE = SUBSTR(t.SEX, 1, 1)) 
   AND EXISTS (SELECT 1 FROM UDW_DIM_COUNTRY c WHERE c.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3)) 
   AND NOT EXISTS (SELECT 1 FROM UDW_FACT_EDUCATION f WHERE f.YEAR_CODE = t.TIME_PERIOD AND f.GENDER_CODE = SUBSTR(t.SEX, 1, 1) AND f.COUNTRY_CODE = SUBSTR(t.REF_AREA, 1, 3)) 
 GROUP BY TIME_PERIOD 
          ,SUBSTR(t.SEX, 1, 1) 
          ,SUBSTR(t.REF_AREA, 1, 3)
;
 
commit;

